spring:
  application:
    name: demo-app1
authn:
  cas:
    prefix: http://localhost:8443/cas
    service-prefix: http://localhost:8091
    service: ${authn.cas.service-prefix}/server/login/cas
    logout-success-url: ${authn.cas.service-prefix}/
server:
  port: 8091
logging:
  level:
    "org.springframework.security.cas": debug